name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry install --with tests --without dev,docs
      # - run: poetry run # TODO: Add tests here
      - name: Check packaging
        run: |
          echo "Building packages"
          poetry build
          echo "Validating packages"
          poetry run twine check dist/*
          echo "Packages build and valdiate successfully."
